[project]
name = "Gru"
version = "0.0.0"
authors = [{name="Cimbali", email="me@cimba.li" }]
description = "Gru gets/removes/updates your ESO add-ons. Nothing to do with being minions’ boss."
readme = "README.md"
license = "MIT"
dependencies = ["requests", "requests-cache", "click", "click-repl", "unicodedata2", "charset-normalizer", "aiofiles", "aioshutil", "httpx", "diff-match-patch"]
requires-python = ">=3.9"

[project.optional-dependencies]
test = [
  "pytest",
  "pytest-mock",
  "pyright",
]

[project.scripts]
gru = "gru.cli:main"

[options]
packages = ["gru"]

[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"
