[project]
name = "Gru"
version = "0.0.0"
authors = [{name="Cimbali", email="me@cimba.li" }]
description = "Gru gets/removes/updates your ESO add-ons. Nothing to do with being minions’ boss."
readme = "README.md"
license = {text = "MIT License"}
dependencies = ["requests", "requests-cache", "click", "unicodedata2", "charset-normalizer"]
requires-python = ">=3.8"

[project.optional-dependencies]
test = [
  "pytest",
]

[project.scripts]
gru = "gru.cli:main"

[options]
packages = ["gru"]

[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"
